#!/usr/bin/env bash
# clean.sh — Remove all regenerable files to reclaim disk space.
#
# Everything deleted here is recreated by running the pipeline (see start-here.md).
# The raw TCGA expression matrix alone is ~316 MB and takes ~30 min to redownload.
#
# Usage:
#   ./clean.sh          # dry-run: shows what would be deleted
#   ./clean.sh --force  # actually deletes

DRY_RUN=true
if [[ "$1" == "--force" ]]; then
  DRY_RUN=false
fi

remove() {
  local target="$1"
  if [[ -e "$target" || -d "$target" ]]; then
    local size
    size=$(du -sh "$target" 2>/dev/null | cut -f1)
    echo "  [${size}]  $target"
    if [[ "$DRY_RUN" == false ]]; then
      rm -rf "$target"
    fi
  fi
}

echo ""
if [[ "$DRY_RUN" == true ]]; then
  echo "DRY RUN — nothing will be deleted. Pass --force to actually clean."
else
  echo "Cleaning regenerable files..."
fi
echo ""

echo "==> Data files (regenerated by notebooks 01–03)"
remove data/

echo ""
echo "==> Figures (regenerated by notebooks 02–06)"
remove figures/

echo ""
echo "==> Generated reports"
remove cold_tumor_p16_report.pdf
remove paper/manuscript.pdf
remove paper/manuscript.aux
remove paper/manuscript.log
remove paper/manuscript.out
remove notebooks/04_overlap_analysis.html
remove notebooks/05_survival.html

echo ""
echo "==> Python / Jupyter caches"
find . -type d -name "__pycache__" | while read -r d; do remove "$d"; done
find . -type d -name ".ipynb_checkpoints" | while read -r d; do remove "$d"; done
find . -name ".DS_Store" | while read -r f; do remove "$f"; done

echo ""
if [[ "$DRY_RUN" == true ]]; then
  echo "Run './clean.sh --force' to delete the above."
else
  echo "Done. Re-run the pipeline (start-here.md) to regenerate everything."
fi
echo ""
